apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-orchestrion-go
    tags.datadoghq.com/env: staging
    tags.datadoghq.com/service: simple-orchestrion-go
    tags.datadoghq.com/version: 1.0.0
  name: simple-orchestrion-go
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-orchestrion-go
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
        app: simple-orchestrion-go
        tags.datadoghq.com/env: staging
        tags.datadoghq.com/service: simple-orchestrion-go
        tags.datadoghq.com/version: 1.0.0
    spec:
      containers:
        - name: go
          image: mmeeww/simple-go:0a61c08d4d4882f583b03b32d8b87365630190d1
          env:
            - name: DD_TRACE_DEBUG
              value: "true"
